"""Q05 — Stress MEDIUM runner.

Per Vault Q05 spec:
  Slippage: +2 pips
  Spread:   × 2 broker baseline
  Commission: × 2 baseline (FW2/FW5 multiplier)
  Trade-rejection: 0% (Q06 HARSH only)
  Window: full available history per symbol
  Verdict: PF > 1.0 AND DD < 15%

Per-symbol verdict; runs per Q04-PASS entry using the Q03 plateau-median
parameters with the stress setfile generated by gen_stress_setfile.py.
"""

from __future__ import annotations

import argparse
from html import unescape
import json
import re
import subprocess
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from framework.scripts._phase_utils import (ensure_dir, utc_now_iso, write_json,
                                            resolve_ea_expert_path, period_from_setfile,
                                            find_latest_summary, full_history_window)

GATE_NAME = "Q05"
LEVEL = "MED"
PF_FLOOR = 1.0
DD_PCT_MAX = 15.0
MIN_TRADES = 20
STARTING_EQUITY = 100_000.0
INVALID_SUMMARY_REASON_CLASSES = {
    "NO_HISTORY",
    "NO_HISTORY_LOG",
    "NO_REAL_TICKS",
    "REPORT_MISSING",
    "REPORT_PARSE_ERROR",
    "REPORT_FORMAT_DRIFT",
    "INVALID_REPORT",
    "INCOMPLETE_RUNS",
    "ONINIT_FAILED",
    "BARS_ZERO",
    "HISTORY_CONTEXT_INVALID",
    "TIMEOUT",
}
INVALID_REPORT_MARKERS = {
    "EMPTY_EXPERT",
    "EMPTY_SYMBOL",
    "M0_1970_PERIOD",
    "BARS_ZERO",
    "HISTORY_CONTEXT_INVALID",
    "REPORT_METRIC_MISSING:EXPERT",
    "REPORT_METRIC_MISSING:PERIOD",
    "REPORT_METRIC_MISSING:BARS",
    "ONINIT_FAILED",
}


def _load_summary(summary_path: Path) -> dict | None:
    if not summary_path.exists():
        return None
    try:
        return json.loads(summary_path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return None


def summary_invalid_reason(summary_path: Path) -> str | None:
    """Return an infra/data invalidation reason for malformed run_smoke summaries.

    A 0-trade result is only a strategy result if the MT5 report is valid. Empty
    expert/symbol, M0/1970, no bars/history, locale/report parser drift, or an
    INVALID run means the evidence did not run cleanly and must not collapse into
    `trades_below_floor`.
    """
    sj = _load_summary(summary_path)
    if sj is None:
        return "summary_parse_error"
    reasons = {str(r).upper() for r in (sj.get("reason_classes") or [])}
    runs = sj.get("runs") or []
    markers: set[str] = set()
    for run in runs:
        if str(run.get("status") or "").upper() == "INVALID":
            markers.add("RUN_STATUS_INVALID")
        for reason in run.get("invalid_report_reasons") or []:
            markers.add(str(reason).upper())
        if run.get("failure"):
            markers.add(str(run.get("failure")).upper())
    invalid = sorted((reasons & INVALID_SUMMARY_REASON_CLASSES) | (markers & INVALID_REPORT_MARKERS))
    if markers and "RUN_STATUS_INVALID" in markers:
        invalid.append("RUN_STATUS_INVALID")
    if invalid:
        return "invalid_summary:" + ",".join(dict.fromkeys(invalid))
    return None


def _parse_pf_dd_trades(summary_path: Path) -> tuple[float | None, float | None, int]:
    sj = _load_summary(summary_path)
    if sj is None:
        return None, None, 0
    runs = sj.get("runs") or []
    if not runs:
        return None, None, 0
    r0 = runs[-1]
    def _optional_float(value: object) -> float | None:
        if value is None or value == "":
            return None
        return float(value)
    try:
        pf = _optional_float(r0.get("profit_factor"))
        dd_money = _optional_float(r0.get("drawdown"))
        trades = int(r0.get("total_trades") or 0)
    except (TypeError, ValueError):
        return None, None, 0
    return pf, dd_money, trades


def _clean_report_cell(raw: str) -> str:
    text = re.sub(r"<[^>]+>", "", raw)
    return unescape(text).replace("\xa0", " ").strip()


def _report_cell(html: str, label: str) -> str | None:
    pattern = re.compile(
        rf"<td[^>]*>\s*{re.escape(label)}:\s*</td>\s*<td[^>]*>\s*<b>(.*?)</b>",
        re.IGNORECASE | re.DOTALL,
    )
    match = pattern.search(html)
    return _clean_report_cell(match.group(1)) if match else None


def _parse_report_float(value: str | None) -> float | None:
    if not value:
        return None
    match = re.search(r"-?[\d\s]+(?:[.,]\d+)?", value)
    if not match:
        return None
    text = match.group(0).replace(" ", "").replace(",", ".")
    try:
        return float(text)
    except ValueError:
        return None


def _parse_report_int(value: str | None) -> int | None:
    parsed = _parse_report_float(value)
    return int(parsed) if parsed is not None else None


def _latest_report_metrics(report_root: Path) -> dict | None:
    root = Path(report_root)
    if not root.is_dir():
        return None
    reports = sorted(root.rglob("report.htm"), key=lambda p: p.stat().st_mtime, reverse=True)
    for report in reports:
        try:
            raw = report.read_bytes()
        except (OSError, UnicodeError):
            continue
        html = ""
        for encoding in ("utf-8-sig", "utf-16", "cp1252"):
            try:
                candidate = raw.decode(encoding, errors="replace")
            except UnicodeError:
                continue
            if "<html" in candidate[:500].lower():
                html = candidate
                break
        if not html:
            continue

        expert = _report_cell(html, "Expert")
        symbol = _report_cell(html, "Symbol")
        period = _report_cell(html, "Period")
        bars = _parse_report_int(_report_cell(html, "Bars"))
        if not expert or not symbol or not period or period.upper().startswith("M0 ") or not bars:
            continue

        pf = _parse_report_float(_report_cell(html, "Profit Factor"))
        trades = _parse_report_int(_report_cell(html, "Total Trades"))
        dd_money = (
            _parse_report_float(_report_cell(html, "Equity Drawdown Maximal"))
            or _parse_report_float(_report_cell(html, "Balance Drawdown Maximal"))
            or _parse_report_float(_report_cell(html, "Equity Drawdown Relative"))
            or _parse_report_float(_report_cell(html, "Balance Drawdown Relative"))
        )
        if pf is None or trades is None or dd_money is None:
            continue
        return {
            "report_path": str(report),
            "expert": expert,
            "symbol": symbol,
            "period": period,
            "bars": bars,
            "pf": pf,
            "dd_money": dd_money,
            "trades": trades,
        }
    return None


def gen_stress_setfile_for(baseline: Path) -> Path:
    """Invoke gen_stress_setfile.py to produce the Q05 MED variant."""
    repo_root = Path(__file__).resolve().parents[2]
    gen_script = repo_root / "framework" / "scripts" / "gen_stress_setfile.py"
    args = [sys.executable, str(gen_script), str(baseline),
            "--level", LEVEL, "--in-place"]
    proc = subprocess.run(args, capture_output=True, text=True, timeout=30)
    if proc.returncode != 0:
        raise RuntimeError(f"gen_stress_setfile failed: {proc.stderr or proc.stdout}")
    # Output: same dir, suffix _q05_stress_medium.set
    stem = baseline.stem
    if stem.endswith("_backtest"):
        stem = stem[: -len("_backtest")]
    return baseline.with_name(f"{stem}_q05_stress_medium.set")


def _basket_tester_overrides(setfile: Path) -> tuple[str | None, int | None]:
    """Return tester currency/deposit from the EA basket manifest, if present."""
    manifest_path = Path(setfile).parent.parent / "basket_manifest.json"
    if not manifest_path.exists():
        return None, None
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return None, None

    currency_raw = str(manifest.get("tester_currency") or "").strip().upper()
    currency = currency_raw if re.fullmatch(r"[A-Z]{3}", currency_raw) else None

    deposit = None
    for key in ("tester_deposit", "tester_initial_deposit"):
        try:
            value = int(str(manifest.get(key) or "").strip())
        except ValueError:
            continue
        if value > 0:
            deposit = value
            break
    return currency, deposit


def run_stress_backtest(*, ea_id: int, ea_expert: str, symbol: str,
                         setfile: Path, terminal: str, period: str = "H1",
                         report_root: Path, timeout_sec: int = 1800,
                         latest_full_year: int | None = None,
                         logical_symbol: str | None = None) -> dict:
    repo_root = Path(__file__).resolve().parents[2]
    run_smoke_ps1 = repo_root / "framework" / "scripts" / "run_smoke.ps1"
    history_year, history_from, history_to = full_history_window(latest_full_year)
    evidence_symbol = logical_symbol or symbol
    args = [
        "pwsh.exe", "-NoProfile", "-File", str(run_smoke_ps1),
        "-EAId", str(ea_id),
        "-Expert", ea_expert,
        "-Symbol", symbol,
        "-Year", history_year, "-FromDate", history_from, "-ToDate", history_to,
        "-Terminal", terminal,
        "-Period", period,
        "-DispatchSubGateHash", f"q05_{ea_id}_{symbol.replace('.', '_')}",
        "-DispatchPhase", "Q05",
        "-DispatchVersion", "q05_stress_medium",
        "-Runs", "1",
        "-MinTrades", str(MIN_TRADES),
        "-Model", "4",
        "-SetFile", str(setfile),
        "-ReportRoot", str(report_root),
        "-TimeoutSeconds", str(timeout_sec),
    ]
    tester_currency, tester_deposit = _basket_tester_overrides(setfile)
    if tester_currency:
        args.extend(["-TesterCurrencyOverride", tester_currency])
    if tester_deposit:
        args.extend(["-TesterDepositOverride", str(tester_deposit)])
    creationflags = subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
    runner_timeout_sec = timeout_sec + 120
    timed_out = False
    timeout_detail = None
    try:
        proc = subprocess.run(args, capture_output=True, text=True,
                              timeout=runner_timeout_sec, creationflags=creationflags)
        exit_code = proc.returncode
    except subprocess.TimeoutExpired as exc:
        timed_out = True
        timeout_detail = f"subprocess_timeout_after={exc.timeout}s"
        exit_code = 124
    sym_clean = symbol.replace(".", "_")
    summary = find_latest_summary(report_root)
    invalid_reason = summary_invalid_reason(summary) if summary else None
    report_metrics = None if summary else _latest_report_metrics(report_root)
    if summary:
        pf, dd_money, trades = _parse_pf_dd_trades(summary)
    elif report_metrics:
        pf = report_metrics["pf"]
        dd_money = report_metrics["dd_money"]
        trades = report_metrics["trades"]
    else:
        pf, dd_money, trades = None, None, 0
    dd_pct = (dd_money / STARTING_EQUITY * 100.0) if dd_money is not None else None

    if summary is None and report_metrics is None:
        if timed_out:
            verdict = "INVALID"
            reason = f"timeout_expired:timeout_sec={timeout_sec}:runner_timeout_sec={runner_timeout_sec}"
        else:
            verdict, reason = "INVALID", "summary_missing"
    elif invalid_reason:
        verdict, reason = "INVALID", invalid_reason
    elif trades < MIN_TRADES:
        verdict, reason = "FAIL", f"trades_below_floor:trades={trades}:floor={MIN_TRADES}"
    elif pf is None:
        verdict, reason = "FAIL", f"missing_pf_in_summary:trades={trades}"
    elif dd_money is None:
        verdict, reason = "FAIL", f"missing_dd_in_summary:trades={trades}"
    elif pf <= PF_FLOOR:
        verdict, reason = "FAIL", f"pf_below_floor:pf={pf:.3f}:floor={PF_FLOOR}"
    elif dd_pct > DD_PCT_MAX:
        verdict, reason = "FAIL", f"dd_above_ceiling:dd_pct={dd_pct:.2f}:max={DD_PCT_MAX}"
    else:
        verdict, reason = "PASS", f"pf={pf:.3f}:dd_pct={dd_pct:.2f}"

    return {
        "phase": GATE_NAME,
        "ea_id": ea_id,
        "symbol": evidence_symbol,
        "runner_symbol": symbol,
        "verdict": verdict,
        "reason": reason,
        "pf": pf,
        "dd_money": dd_money,
        "dd_pct": dd_pct,
        "trades": trades,
        "exit_code": exit_code,
        "timed_out": timed_out,
        "timeout_detail": timeout_detail,
        "timeout_sec": timeout_sec,
        "runner_timeout_sec": runner_timeout_sec,
        "summary_path": str(summary) if summary else None,
        "report_path": report_metrics.get("report_path") if report_metrics else None,
        "metric_source": "summary_json" if summary else ("report_htm" if report_metrics else None),
        "history_year": history_year,
        "history_from": history_from,
        "history_to": history_to,
        "latest_full_year": latest_full_year,
        "generated_at_utc": utc_now_iso(),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Q05 Stress MEDIUM runner")
    ap.add_argument("--ea", required=True)
    ap.add_argument("--symbol", required=True)
    ap.add_argument("--baseline-setfile", type=Path, required=True,
                    help="Q03 plateau-median setfile; Q05 stress variant generated from this")
    ap.add_argument("--terminal", default="T2")
    ap.add_argument("--report-root", type=Path, default=Path("D:/QM/reports/pipeline"))
    ap.add_argument("--timeout-sec", type=int, default=1800)
    ap.add_argument("--latest-full-year", type=int,
                    help="Cap full-history window when validated custom-symbol history ends before default")
    ap.add_argument("--logical-symbol",
                    help="Basket evidence symbol to record when --symbol is the MT5 host")
    args = ap.parse_args()

    ea_match = re.match(r"QM5_(\d+)_?", args.ea)
    if not ea_match:
        print(f"bad EA label: {args.ea}", file=sys.stderr)
        return 2
    ea_id = int(ea_match.group(1))

    repo_root = Path(__file__).resolve().parents[2]
    ea_expert = resolve_ea_expert_path(repo_root, args.ea)
    if ea_expert is None:
        print(f"cannot resolve EA dir for {args.ea}", file=sys.stderr)
        return 2
    period = period_from_setfile(args.baseline_setfile)

    stress_set = gen_stress_setfile_for(args.baseline_setfile)
    print(f"Q05 MED: generated stress setfile {stress_set.name}")

    res = run_stress_backtest(
        ea_id=ea_id, ea_expert=ea_expert, symbol=args.symbol,
        setfile=stress_set, terminal=args.terminal, period=period,
        report_root=args.report_root, timeout_sec=args.timeout_sec,
        latest_full_year=args.latest_full_year,
        logical_symbol=args.logical_symbol,
    )

    evidence_symbol = args.logical_symbol or args.symbol
    out_dir = ensure_dir(args.report_root / f"QM5_{ea_id}" / "Q05" / evidence_symbol.replace(".", "_"))
    write_json(out_dir / "aggregate.json", res)
    print(f"Q05 {args.ea} {evidence_symbol}: {res['verdict']}  pf={res['pf']}  dd_pct={res['dd_pct']}")
    return 0 if res["verdict"] == "PASS" else (1 if res["verdict"] == "FAIL" else 3)


if __name__ == "__main__":
    sys.exit(main())
