"""Q05 — Stress MEDIUM runner.

Per Vault Q05 spec:
  Slippage: +2 pips
  Spread:   × 2 broker baseline
  Commission: × 2 baseline (FW2/FW5 multiplier)
  Trade-rejection: 0% (Q06 HARSH only)
  Window: full available history per symbol
  Verdict: PF > 1.0 AND DD < 15%

Per-symbol verdict; runs per Q04-PASS entry using the Q03 plateau-median
parameters with the stress setfile generated by gen_stress_setfile.py.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from framework.scripts._phase_utils import (ensure_dir, utc_now_iso, write_json,
                                            resolve_ea_expert_path, period_from_setfile,
                                            find_latest_summary, FULL_HISTORY_FROM,
                                            FULL_HISTORY_TO, FULL_HISTORY_YEAR)

GATE_NAME = "Q05"
LEVEL = "MED"
PF_FLOOR = 1.0
DD_PCT_MAX = 15.0
MIN_TRADES = 20
STARTING_EQUITY = 100_000.0


def _parse_pf_dd_trades(summary_path: Path) -> tuple[float | None, float | None, int]:
    import json
    if not summary_path.exists():
        return None, None, 0
    try:
        sj = json.loads(summary_path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return None, None, 0
    runs = sj.get("runs") or []
    if not runs:
        return None, None, 0
    r0 = runs[-1]
    def _optional_float(value: object) -> float | None:
        if value is None or value == "":
            return None
        return float(value)
    try:
        pf = _optional_float(r0.get("profit_factor"))
        dd_money = _optional_float(r0.get("drawdown"))
        trades = int(r0.get("total_trades") or 0)
    except (TypeError, ValueError):
        return None, None, 0
    return pf, dd_money, trades


def gen_stress_setfile_for(baseline: Path) -> Path:
    """Invoke gen_stress_setfile.py to produce the Q05 MED variant."""
    repo_root = Path(__file__).resolve().parents[2]
    gen_script = repo_root / "framework" / "scripts" / "gen_stress_setfile.py"
    args = [sys.executable, str(gen_script), str(baseline),
            "--level", LEVEL, "--in-place"]
    proc = subprocess.run(args, capture_output=True, text=True, timeout=30)
    if proc.returncode != 0:
        raise RuntimeError(f"gen_stress_setfile failed: {proc.stderr or proc.stdout}")
    # Output: same dir, suffix _q05_stress_medium.set
    stem = baseline.stem
    if stem.endswith("_backtest"):
        stem = stem[: -len("_backtest")]
    return baseline.with_name(f"{stem}_q05_stress_medium.set")


def run_stress_backtest(*, ea_id: int, ea_expert: str, symbol: str,
                         setfile: Path, terminal: str, period: str = "H1",
                         report_root: Path, timeout_sec: int = 1800) -> dict:
    repo_root = Path(__file__).resolve().parents[2]
    run_smoke_ps1 = repo_root / "framework" / "scripts" / "run_smoke.ps1"
    args = [
        "pwsh.exe", "-NoProfile", "-File", str(run_smoke_ps1),
        "-EAId", str(ea_id),
        "-Expert", ea_expert,
        "-Symbol", symbol,
        "-Year", FULL_HISTORY_YEAR, "-FromDate", FULL_HISTORY_FROM, "-ToDate", FULL_HISTORY_TO,
        "-Terminal", terminal,
        "-Period", period,
        "-DispatchSubGateHash", f"q05_{ea_id}_{symbol.replace('.', '_')}",
        "-DispatchPhase", "Q05",
        "-DispatchVersion", "q05_stress_medium",
        "-Runs", "1",
        "-MinTrades", str(MIN_TRADES),
        "-Model", "4",
        "-SetFile", str(setfile),
        "-ReportRoot", str(report_root),
        "-TimeoutSeconds", str(timeout_sec),
    ]
    creationflags = subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
    proc = subprocess.run(args, capture_output=True, text=True,
                          timeout=timeout_sec, creationflags=creationflags)
    sym_clean = symbol.replace(".", "_")
    summary = find_latest_summary(report_root)
    pf, dd_money, trades = _parse_pf_dd_trades(summary) if summary else (None, None, 0)
    dd_pct = (dd_money / STARTING_EQUITY * 100.0) if dd_money is not None else None

    if summary is None:
        verdict, reason = "INVALID", "summary_missing"
    elif trades < MIN_TRADES:
        verdict, reason = "FAIL", f"trades_below_floor:trades={trades}:floor={MIN_TRADES}"
    elif pf is None:
        verdict, reason = "FAIL", f"missing_pf_in_summary:trades={trades}"
    elif dd_money is None:
        verdict, reason = "FAIL", f"missing_dd_in_summary:trades={trades}"
    elif pf <= PF_FLOOR:
        verdict, reason = "FAIL", f"pf_below_floor:pf={pf:.3f}:floor={PF_FLOOR}"
    elif dd_pct > DD_PCT_MAX:
        verdict, reason = "FAIL", f"dd_above_ceiling:dd_pct={dd_pct:.2f}:max={DD_PCT_MAX}"
    else:
        verdict, reason = "PASS", f"pf={pf:.3f}:dd_pct={dd_pct:.2f}"

    return {
        "phase": GATE_NAME,
        "ea_id": ea_id,
        "symbol": symbol,
        "verdict": verdict,
        "reason": reason,
        "pf": pf,
        "dd_money": dd_money,
        "dd_pct": dd_pct,
        "trades": trades,
        "exit_code": proc.returncode,
        "summary_path": str(summary) if summary else None,
        "generated_at_utc": utc_now_iso(),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Q05 Stress MEDIUM runner")
    ap.add_argument("--ea", required=True)
    ap.add_argument("--symbol", required=True)
    ap.add_argument("--baseline-setfile", type=Path, required=True,
                    help="Q03 plateau-median setfile; Q05 stress variant generated from this")
    ap.add_argument("--terminal", default="T2")
    ap.add_argument("--report-root", type=Path, default=Path("D:/QM/reports/pipeline"))
    ap.add_argument("--timeout-sec", type=int, default=1800)
    args = ap.parse_args()

    ea_match = re.match(r"QM5_(\d+)_?", args.ea)
    if not ea_match:
        print(f"bad EA label: {args.ea}", file=sys.stderr)
        return 2
    ea_id = int(ea_match.group(1))

    repo_root = Path(__file__).resolve().parents[2]
    ea_expert = resolve_ea_expert_path(repo_root, args.ea)
    if ea_expert is None:
        print(f"cannot resolve EA dir for {args.ea}", file=sys.stderr)
        return 2
    period = period_from_setfile(args.baseline_setfile)

    stress_set = gen_stress_setfile_for(args.baseline_setfile)
    print(f"Q05 MED: generated stress setfile {stress_set.name}")

    res = run_stress_backtest(
        ea_id=ea_id, ea_expert=ea_expert, symbol=args.symbol,
        setfile=stress_set, terminal=args.terminal, period=period,
        report_root=args.report_root, timeout_sec=args.timeout_sec,
    )

    out_dir = ensure_dir(args.report_root / f"QM5_{ea_id}" / "Q05" / args.symbol.replace(".", "_"))
    write_json(out_dir / "aggregate.json", res)
    print(f"Q05 {args.ea} {args.symbol}: {res['verdict']}  pf={res['pf']}  dd_pct={res['dd_pct']}")
    return 0 if res["verdict"] == "PASS" else (1 if res["verdict"] == "FAIL" else 3)


if __name__ == "__main__":
    sys.exit(main())
