"""Contract section 8 - MQL5<->Python DST parity, dense sweep + boundary tests.

Cross-checks ``news_impact_mapping.py``'s ``qm.dst_rule.us.v1`` port against
``docs/ops/evidence/2026-09-14_dst_cross_language_parity/golden_table.csv``, generated by
``tools/strategy_farm/dst_rule_golden_table.py`` - a *from-scratch*, independently coded
re-implementation of the same textual rule (see that module's docstring for why an
independent second implementation is stronger evidence than self-comparison).

The same golden table's boundary instants are also embedded (as generated, not
hand-picked, literals) in ``framework/tests/unit/dst_aware_transition_tests.mq5``, so a
future compile+run of that MQL5 unit test checks the live-validated MQL5
``QM_DSTAware.mqh`` against this exact table too - the three-way agreement (golden
generator, Python port, MQL5 original) is the cross-language parity the contract asks for.
"""

import csv
import sys
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "tools" / "strategy_farm"))

import news_impact_mapping as nim  # noqa: E402
import dst_rule_golden_table as golden  # noqa: E402

GOLDEN_CSV = REPO / "docs/ops/evidence/2026-09-14_dst_cross_language_parity/golden_table.csv"


def _load_golden_rows():
    with GOLDEN_CSV.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


class GoldenTableSanityTests(unittest.TestCase):
    """The table itself must actually be dense and span what section 8 requires."""

    def test_golden_table_exists_and_is_dense(self):
        rows = _load_golden_rows()
        self.assertGreater(len(rows), 3000)

    def test_golden_table_spans_a_leap_and_non_leap_year(self):
        years = {int(row["utc_iso"][:4]) for row in _load_golden_rows()}
        self.assertIn(2024, years)  # leap
        self.assertTrue({2023, 2025, 2026, 2027} & years)  # non-leap
        self.assertGreaterEqual(len(years), 3)

    def test_golden_table_has_no_duplicate_timestamps(self):
        rows = _load_golden_rows()
        stamps = [row["utc_iso"] for row in rows]
        self.assertEqual(len(stamps), len(set(stamps)), "duplicate utc_iso in golden table")

    def test_golden_generator_agrees_with_the_already_shipped_mql5_literal(self):
        """framework/tests/unit/dst_aware_transition_tests.mq5 already asserts 2026
        boundaries against StringToTime literals; the independent generator must
        reproduce the exact same instants (a third confirmation point)."""

        self.assertEqual(golden.us_dst_start_utc(2026), datetime(2026, 3, 8, 7, 0, tzinfo=timezone.utc))
        self.assertEqual(golden.us_dst_end_utc(2026), datetime(2026, 11, 1, 6, 0, tzinfo=timezone.utc))


class PythonVsGoldenParityTests(unittest.TestCase):
    """Every golden row: nim's ported rule must agree bit-for-bit with the independent
    reference implementation - dense sweep, no off-by-one at either boundary."""

    def test_every_golden_row_matches_is_us_dst_and_offset(self):
        rows = _load_golden_rows()
        mismatches = []
        for row in rows:
            moment = datetime.strptime(row["utc_iso"], "%Y-%m-%dT%H:%M:%SZ").replace(
                tzinfo=timezone.utc
            )
            expected_dst = bool(int(row["is_us_dst"]))
            expected_offset = int(row["offset_hours"])
            got_dst = nim.is_us_dst_utc(moment)
            got_offset = nim.broker_offset_hours(moment)
            if got_dst != expected_dst or got_offset != expected_offset:
                mismatches.append((row["utc_iso"], expected_dst, got_dst, expected_offset, got_offset))
        self.assertEqual(
            mismatches, [], f"{len(mismatches)} golden-table mismatches (showing all): {mismatches}"
        )

    def test_every_golden_row_matches_broker_time(self):
        rows = _load_golden_rows()
        mismatches = []
        for row in rows:
            moment = datetime.strptime(row["utc_iso"], "%Y-%m-%dT%H:%M:%SZ").replace(
                tzinfo=timezone.utc
            )
            expected_broker = row["broker_time_iso"]
            got_broker = nim.utc_to_broker(moment).strftime("%Y-%m-%dT%H:%M:%S")
            if got_broker != expected_broker:
                mismatches.append((row["utc_iso"], expected_broker, got_broker))
        self.assertEqual(mismatches, [])

    def test_no_off_by_one_at_either_boundary_for_every_year(self):
        minute = timedelta(minutes=1)
        for year in golden.YEARS:
            start = golden.us_dst_start_utc(year).replace(tzinfo=timezone.utc)
            end = golden.us_dst_end_utc(year).replace(tzinfo=timezone.utc)
            with self.subTest(year=year, boundary="start"):
                self.assertFalse(nim.is_us_dst_utc(start - minute))
                self.assertTrue(nim.is_us_dst_utc(start))
                self.assertEqual(nim.broker_offset_hours(start - minute), 2)
                self.assertEqual(nim.broker_offset_hours(start), 3)
            with self.subTest(year=year, boundary="end"):
                self.assertTrue(nim.is_us_dst_utc(end - minute))
                self.assertFalse(nim.is_us_dst_utc(end))
                self.assertEqual(nim.broker_offset_hours(end - minute), 3)
                self.assertEqual(nim.broker_offset_hours(end), 2)

    def test_november_fallback_ambiguous_hour_prefers_standard_time(self):
        """Contract section 8(c): broker_time -> utc resolves to the UTC+2 candidate."""

        for year in golden.YEARS:
            end = golden.us_dst_end_utc(year).replace(tzinfo=timezone.utc)
            ambiguous_broker = (end + timedelta(hours=2)).replace(tzinfo=None)
            resolved = nim.broker_to_utc(ambiguous_broker)
            self.assertFalse(nim.is_us_dst_utc(resolved))
            self.assertEqual(resolved, end)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
