#ifndef QM5_1537_MONTHLY_SLEEVE_CALENDAR_MQH
#define QM5_1537_MONTHLY_SLEEVE_CALENDAR_MQH

// EA-local, fail-closed loader for the calendar generated by
// tools/build_monthly_sleeve_calendar.py. Runtime reads FILE_COMMON only and
// never selects or reads a foreign market symbol.

#define QM1537_SLEEVE_SCHEMA     "qm1537.monthly_sleeve.v1"
#define QM1537_SLEEVE_TIE_BREAK  "basket_slot_ascending"
#define QM1537_SLEEVE_EVALUATION "first_host_d1_bar_of_calendar_month"

bool   g_qm1537_calendar_ready = false;
string g_qm1537_calendar_error = "not_loaded";
string g_qm1537_calendar_actual_sha256 = "";
string g_qm1537_calendar_contract_sha256 = "";
string g_qm1537_calendar_input_bundle_sha256 = "";
int    g_qm1537_calendar_months[];
int    g_qm1537_calendar_host_ranks[];
int    g_qm1537_calendar_valid_counts[];
bool   g_qm1537_calendar_selected[];
double g_qm1537_calendar_host_vol_pct[];
long   g_qm1537_calendar_asof_epoch[];

string QM1537_Trimmed(string value)
  {
   StringTrimLeft(value);
   StringTrimRight(value);
   return value;
  }

string QM1537_Upper(string value)
  {
   StringToUpper(value);
   return value;
  }

bool QM1537_IsSha256(const string value)
  {
   if(StringLen(value) != 64)
      return false;
   const string hex = "0123456789abcdefABCDEF";
   for(int i = 0; i < 64; ++i)
     {
      if(StringFind(hex, StringSubstr(value, i, 1)) < 0)
         return false;
     }
   return true;
  }

bool QM1537_IsUnsignedInteger(const string value)
  {
   if(StringLen(value) <= 0)
      return false;
   const string digits = "0123456789";
   for(int i = 0; i < StringLen(value); ++i)
     {
      if(StringFind(digits, StringSubstr(value, i, 1)) < 0)
         return false;
     }
   return true;
  }

bool QM1537_HashBytes(uchar &bytes[], string &hash_hex)
  {
   hash_hex = "";
   uchar digest[];
   uchar key[];
   ArrayResize(key, 0);
   const int digest_size = CryptEncode(CRYPT_HASH_SHA256, bytes, key, digest);
   if(digest_size != 32)
      return false;
   for(int i = 0; i < digest_size; ++i)
      hash_hex += StringFormat("%02X", digest[i]);
   return true;
  }

bool QM1537_HashTextUtf8(const string value, string &hash_hex)
  {
   uchar bytes[];
   const int copied = StringToCharArray(value, bytes, 0, -1, CP_UTF8);
   if(copied <= 0)
      return false;
   int size = copied;
   if(size > 0 && bytes[size - 1] == 0)
      size--;
   if(ArrayResize(bytes, size) != size)
      return false;
   return QM1537_HashBytes(bytes, hash_hex);
  }

bool QM1537_CommonFileSha256(const string file_name, string &hash_hex)
  {
   hash_hex = "";
   const int handle = FileOpen(file_name,
                               FILE_READ | FILE_BIN | FILE_SHARE_READ |
                               FILE_COMMON);
   if(handle == INVALID_HANDLE)
      return false;
   const int size = (int)FileSize(handle);
   if(size <= 0)
     {
      FileClose(handle);
      return false;
     }
   uchar bytes[];
   if(ArrayResize(bytes, size) != size ||
      FileReadArray(handle, bytes, 0, size) != size)
     {
      FileClose(handle);
      return false;
     }
   FileClose(handle);
   return QM1537_HashBytes(bytes, hash_hex);
  }

string Strategy_RankingContractPayload()
  {
   string universe = "";
   for(int i = 0; i < ArraySize(g_strategy_basket); ++i)
     {
      if(i > 0)
         universe += ",";
      universe += g_strategy_basket[i];
     }
   return StringFormat(
      "schema=%s|min_daily_bars=%d|vol_lookback_days=%d|annualization_days=%d|top_n=%d|tie_break=%s|evaluation=%s|universe=%s",
      QM1537_SLEEVE_SCHEMA,
      strategy_min_daily_bars,
      strategy_vol_lookback_days,
      strategy_vol_annualization_days,
      strategy_top_symbols,
      QM1537_SLEEVE_TIE_BREAK,
      QM1537_SLEEVE_EVALUATION,
      universe);
  }

bool QM1537_KnownSymbol(const string symbol)
  {
   if(symbol == "")
      return false;
   for(int i = 0; i < ArraySize(g_strategy_basket); ++i)
     {
      if(g_strategy_basket[i] == symbol)
         return true;
     }
   return false;
  }

bool QM1537_ValidMonthKey(const int value)
  {
   const int year = value / 100;
   const int month = value % 100;
   return (year >= 2000 && year <= 2999 && month >= 1 && month <= 12);
  }

bool QM1537_AsOfMatchesMonth(const long asof_epoch, const int month_key)
  {
   if(asof_epoch <= 0)
      return false;
   MqlDateTime value;
   if(!TimeToStruct((datetime)asof_epoch, value))
      return false;
   return (value.year * 100 + value.mon == month_key);
  }

bool QM1537_CalendarFail(const string detail)
  {
   g_qm1537_calendar_ready = false;
   g_qm1537_calendar_error = detail;
   ArrayResize(g_qm1537_calendar_months, 0);
   ArrayResize(g_qm1537_calendar_host_ranks, 0);
   ArrayResize(g_qm1537_calendar_valid_counts, 0);
   ArrayResize(g_qm1537_calendar_selected, 0);
   ArrayResize(g_qm1537_calendar_host_vol_pct, 0);
   ArrayResize(g_qm1537_calendar_asof_epoch, 0);
   return false;
  }

bool QM1537_CalendarAppend(const int month_key,
                           const int host_rank,
                           const int valid_count,
                           const bool selected,
                           const double host_vol_pct,
                           const long asof_epoch)
  {
   const int n = ArraySize(g_qm1537_calendar_months);
   if(ArrayResize(g_qm1537_calendar_months, n + 1) != n + 1 ||
      ArrayResize(g_qm1537_calendar_host_ranks, n + 1) != n + 1 ||
      ArrayResize(g_qm1537_calendar_valid_counts, n + 1) != n + 1 ||
      ArrayResize(g_qm1537_calendar_selected, n + 1) != n + 1 ||
      ArrayResize(g_qm1537_calendar_host_vol_pct, n + 1) != n + 1 ||
      ArrayResize(g_qm1537_calendar_asof_epoch, n + 1) != n + 1)
      return false;
   g_qm1537_calendar_months[n] = month_key;
   g_qm1537_calendar_host_ranks[n] = host_rank;
   g_qm1537_calendar_valid_counts[n] = valid_count;
   g_qm1537_calendar_selected[n] = selected;
   g_qm1537_calendar_host_vol_pct[n] = host_vol_pct;
   g_qm1537_calendar_asof_epoch[n] = asof_epoch;
   return true;
  }

bool Strategy_LoadBoundMonthlySleeveCalendar()
  {
   g_qm1537_calendar_ready = false;
   g_qm1537_calendar_error = "load_started";
   g_qm1537_calendar_actual_sha256 = "";
   g_qm1537_calendar_contract_sha256 = "";
   g_qm1537_calendar_input_bundle_sha256 = "";

   const string file_name = QM1537_Trimmed(strategy_sleeve_calendar_file);
   const string expected_file_sha = QM1537_Upper(
      QM1537_Trimmed(strategy_sleeve_calendar_sha256));
   const string expected_contract_sha = QM1537_Upper(
      QM1537_Trimmed(strategy_sleeve_contract_sha256));
   const string expected_bundle_sha = QM1537_Upper(
      QM1537_Trimmed(strategy_sleeve_input_bundle_sha256));
   if(strategy_sleeve_calendar_schema != QM1537_SLEEVE_SCHEMA ||
      file_name == "" || !QM1537_IsSha256(expected_file_sha) ||
      !QM1537_IsSha256(expected_contract_sha) ||
      !QM1537_IsSha256(expected_bundle_sha))
      return QM1537_CalendarFail("invalid_calendar_binding_inputs");

   string computed_contract_sha = "";
   if(!QM1537_HashTextUtf8(Strategy_RankingContractPayload(),
                           computed_contract_sha) ||
      QM1537_Upper(computed_contract_sha) != expected_contract_sha)
      return QM1537_CalendarFail("ranking_contract_sha256_mismatch");
   if(!QM1537_CommonFileSha256(file_name,
                               g_qm1537_calendar_actual_sha256))
      return QM1537_CalendarFail("runtime_calendar_missing_or_unreadable");
   if(QM1537_Upper(g_qm1537_calendar_actual_sha256) != expected_file_sha)
      return QM1537_CalendarFail("runtime_calendar_sha256_mismatch");

   const int handle = FileOpen(file_name,
                               FILE_READ | FILE_CSV | FILE_ANSI |
                               FILE_SHARE_READ | FILE_COMMON,
                               ',');
   if(handle == INVALID_HANDLE)
      return QM1537_CalendarFail("runtime_calendar_csv_open_failed");

   string headers[13] =
     {
      "schema_version", "contract_sha256", "input_bundle_sha256",
      "month_key", "host_symbol", "host_rank", "valid_count", "selected",
      "selected_1", "selected_2", "selected_3", "host_vol_pct", "asof_epoch"
     };
   for(int i = 0; i < ArraySize(headers); ++i)
     {
      if(QM1537_Trimmed(FileReadString(handle)) != headers[i])
        {
         FileClose(handle);
         return QM1537_CalendarFail("runtime_calendar_csv_header_invalid");
        }
     }

   int previous_host_month = 0;
   int host_rows = 0;
   while(!FileIsEnding(handle))
     {
      const string schema = QM1537_Trimmed(FileReadString(handle));
      const string contract_sha = QM1537_Upper(QM1537_Trimmed(FileReadString(handle)));
      const string bundle_sha = QM1537_Upper(QM1537_Trimmed(FileReadString(handle)));
      const string month_text = QM1537_Trimmed(FileReadString(handle));
      const string host_symbol = QM1537_Trimmed(FileReadString(handle));
      const string rank_text = QM1537_Trimmed(FileReadString(handle));
      const string valid_text = QM1537_Trimmed(FileReadString(handle));
      const string selected_text = QM1537_Trimmed(FileReadString(handle));
      const string selected_1 = QM1537_Trimmed(FileReadString(handle));
      const string selected_2 = QM1537_Trimmed(FileReadString(handle));
      const string selected_3 = QM1537_Trimmed(FileReadString(handle));
      const string host_vol_text = QM1537_Trimmed(FileReadString(handle));
      const string asof_text = QM1537_Trimmed(FileReadString(handle));
      if(schema == "" && contract_sha == "" && bundle_sha == "" &&
         month_text == "" && host_symbol == "" && rank_text == "" &&
         valid_text == "" && selected_text == "" && selected_1 == "" &&
         selected_2 == "" && selected_3 == "" && host_vol_text == "" &&
         asof_text == "")
         continue;
      if(schema != QM1537_SLEEVE_SCHEMA ||
         contract_sha != expected_contract_sha ||
         bundle_sha != expected_bundle_sha)
        {
         FileClose(handle);
         return QM1537_CalendarFail("runtime_calendar_row_binding_mismatch");
        }
      if(host_symbol != _Symbol)
         continue;

      const bool rank_is_minus_one = (rank_text == "-1");
      if(!QM1537_IsUnsignedInteger(month_text) ||
         (!rank_is_minus_one && !QM1537_IsUnsignedInteger(rank_text)) ||
         !QM1537_IsUnsignedInteger(valid_text) ||
         (selected_text != "0" && selected_text != "1") ||
         !QM1537_IsUnsignedInteger(asof_text))
        {
         FileClose(handle);
         return QM1537_CalendarFail("runtime_calendar_host_numeric_field_invalid");
        }
      const int month_key = (int)StringToInteger(month_text);
      const int host_rank = rank_is_minus_one ? -1 : (int)StringToInteger(rank_text);
      const int valid_count = (int)StringToInteger(valid_text);
      const bool selected = (selected_text == "1");
      const double host_vol_pct = StringToDouble(host_vol_text);
      const long asof_epoch = StringToInteger(asof_text);
      const bool host_listed = (selected_1 == _Symbol ||
                                selected_2 == _Symbol ||
                                selected_3 == _Symbol);
      if(!QM1537_ValidMonthKey(month_key) || month_key <= previous_host_month ||
         valid_count < 0 || valid_count > ArraySize(g_strategy_basket) ||
         host_rank < -1 || host_rank >= valid_count ||
         host_vol_pct < 0.0 || !MathIsValidNumber(host_vol_pct) ||
         !QM1537_AsOfMatchesMonth(asof_epoch, month_key) ||
         (selected != host_listed) ||
         (selected != (host_rank >= 0 && host_rank < strategy_top_symbols)) ||
         (selected_1 != "" && !QM1537_KnownSymbol(selected_1)) ||
         (selected_2 != "" && !QM1537_KnownSymbol(selected_2)) ||
         (selected_3 != "" && !QM1537_KnownSymbol(selected_3)) ||
         (selected_1 != "" && selected_1 == selected_2) ||
         (selected_1 != "" && selected_1 == selected_3) ||
         (selected_2 != "" && selected_2 == selected_3))
        {
         FileClose(handle);
         return QM1537_CalendarFail("runtime_calendar_host_row_invalid");
        }
      if(!QM1537_CalendarAppend(month_key,
                                host_rank,
                                valid_count,
                                selected,
                                host_vol_pct,
                                asof_epoch))
        {
         FileClose(handle);
         return QM1537_CalendarFail("runtime_calendar_array_append_failed");
        }
      previous_host_month = month_key;
      host_rows++;
     }
   FileClose(handle);
   if(host_rows <= 0)
      return QM1537_CalendarFail("runtime_calendar_host_rows_missing");

   g_qm1537_calendar_contract_sha256 = expected_contract_sha;
   g_qm1537_calendar_input_bundle_sha256 = expected_bundle_sha;
   g_qm1537_calendar_error = "";
   g_qm1537_calendar_ready = true;
   QM_LogEvent(QM_INFO,
               "SLEEVE_CALENDAR_INIT",
               StringFormat(
                  "{\"host\":\"%s\",\"rows\":%d,\"first_month\":%d,\"last_month\":%d,\"calendar_sha256\":\"%s\",\"contract_sha256\":\"%s\",\"input_bundle_sha256\":\"%s\"}",
                  _Symbol,
                  host_rows,
                  g_qm1537_calendar_months[0],
                  g_qm1537_calendar_months[host_rows - 1],
                  g_qm1537_calendar_actual_sha256,
                  g_qm1537_calendar_contract_sha256,
                  g_qm1537_calendar_input_bundle_sha256));
   return true;
  }

bool Strategy_ReadMonthlySleeve(const int month_key,
                                bool &selected,
                                double &host_vol_pct,
                                int &host_rank,
                                int &valid_count,
                                long &asof_epoch)
  {
   selected = false;
   host_vol_pct = 0.0;
   host_rank = -1;
   valid_count = 0;
   asof_epoch = 0;
   if(!g_qm1537_calendar_ready || !QM1537_ValidMonthKey(month_key))
      return false;
   int low = 0;
   int high = ArraySize(g_qm1537_calendar_months) - 1;
   while(low <= high)
     {
      const int middle = low + (high - low) / 2;
      const int value = g_qm1537_calendar_months[middle];
      if(value < month_key)
         low = middle + 1;
      else if(value > month_key)
         high = middle - 1;
      else
        {
         selected = g_qm1537_calendar_selected[middle];
         host_vol_pct = g_qm1537_calendar_host_vol_pct[middle];
         host_rank = g_qm1537_calendar_host_ranks[middle];
         valid_count = g_qm1537_calendar_valid_counts[middle];
         asof_epoch = g_qm1537_calendar_asof_epoch[middle];
         return true;
        }
     }
   return false;
  }

string Strategy_SleeveCalendarMissingReason(const int month_key)
  {
   const int n = ArraySize(g_qm1537_calendar_months);
   if(!g_qm1537_calendar_ready || n <= 0)
      return "calendar_not_ready";
   if(month_key > g_qm1537_calendar_months[n - 1])
      return "calendar_stale";
   if(month_key < g_qm1537_calendar_months[0])
      return "calendar_before_coverage";
   return "calendar_month_missing";
  }

string Strategy_SleeveCalendarLastError()
  {
   return g_qm1537_calendar_error;
  }

#endif // QM5_1537_MONTHLY_SLEEVE_CALENDAR_MQH
