"""Commission the Balke USDJPY range-window sweep tooling (OWNER 2026-09-09 ~21:45Z) as a Codex ticket."""
import json
import subprocess
import time

REPO = "C:/QM/repo"
PLAN = "docs/research/BALKE_WINDOW_SWEEP_PLAN_2026-09-09.md"
T = {
    "requested_by": "Orchestrator Claude interactive session 2026-09-09 (OWNER instruction ~21:45Z: find the best range window by backtests on our own data; plan is pre-registered)",
    "model_tier": "codex_high",
    "codex_model_tier": "terra",
    "codex_reasoning_effort": "high",
    "required_capabilities": ["code", "ops"],
    "title": "WINSWEEP tooling: tools/strategy_farm/window_sweep.py (plan | enqueue --stage A|B | report) - run the pre-registered Balke USDJPY range-window sweep (90 windows x 7 years) as OPT_CENSUS cells of program WINSWEEP_QM5_41398_USDJPY_DWX_2019_2025",
    "objective": "Implement and start stage A of the sweep exactly as pre-registered in " + PLAN + " (read it first; every number, the grid, the metric, the plateau rule and the refutation criterion are fixed there and must be copied, not reinterpreted).",
    "spec": [
        "S1 Declaration: create D:/QM/strategy_farm/artifacts/opt_census/WINSWEEP_QM5_41398_USDJPY_DWX_2019_2025/declaration.json with schema qm.window-sweep.v1, the plan file path + its git commit hash (git log -1 --format=%H -- " + PLAN + "), the verbatim grid and selection-rule text from plan sections 3-5, declared_trial_count=90, parameter_count=3, and sha256 of the base setfile and of the QM5_41398 EX5/MQ5 (same artifact identity the DL-089 census pins). Mirror how opt_census.py builds artifact_identity and cell payloads (expected_* fields, evidence_binding_required, priority_track, opt_census_pool, ledger_path, year/from_date/to_date, program_id, cell_key, arm) so the existing OPT_CENSUS worker path (terminal_worker.py, dl089_scheduling.program_id lanes) accepts the rows unchanged. If the worker or scheduler hard-codes DL089 program ids or the DL-089 harness verdict, extend it minimally and generically (a program registry entry), never by weakening a check; document every touched line.",
        "S2 Setfiles: render one setfile per window and year from the DL-089 2019 baseline setfile (D:/QM/strategy_farm/artifacts/opt_census/DL089_QM5_13213_USDJPY_DWX_2019_2025/setfiles/QM5_41398_balke-pattern-repair-opt_USDJPY.DWX_H1_opt_census_2019_baseline.set), changing ONLY strategy_range_start_hour, strategy_range_end_hour (= start+length) and strategy_exit_hour; opt_pp_* stay 0; range_scan_bars must cover the longest window (>= 36 is enough for length<=8 on H1 with the day-key filter - verify in the MQ5 and state it). Stage A grid: start 0..9, length 2..8, end<=13, exit 18 (60 windows). Stage B: exit in {15,16,17,19,20,21} for the top-5 stage-A plateau windows, generated by `plan --stage B` from the stage-A report, never by hand.",
        "S3 Enqueue: deterministic work-item UUIDs (uuid5 over program id + cell key), cell_key WINSWEEP_QM5_41398_USDJPY_DWX_2019_2025:<year>:s<start>_l<length>_x<exit>, phase OPT_CENSUS, kind backtest, symbol USDJPY.DWX, per-year data windows 2019..2025 exactly as the DL-089 cells, verdict taxonomy identical; enqueue is idempotent and dry-run first (print the 420 rows, then --apply). Priority: the same frontier priority the running DL-089 41398 cells carry (read it from a pending row), so both programs interleave; do not lower or delete any existing row.",
        "S4 Report: `report` reads every MEASURED cell summary.json (runs[0]: net_profit, profit_factor, drawdown, total_trades, report_canonical_path) plus the tester report for distinct entry days (entry-day basis) and per-trade volume for the DXZ costing (5 USD per lot round trip), and writes docs/ops/evidence/2026-09-XX_window_sweep_surface.csv (one row per window x year, gross + costed, admissibility flags) and a stage table with DEV score, plateau score, OOS confirmation and the refutation verdict per plan section 5. Report must refuse to select while any of the 7 year-cells of a window is not MEASURED (list them instead).",
        "S5 Run stage A now (dry-run evidence + apply), then report the queue state (rows enqueued, priority, first claim) in OPEN_ITEMS. Do NOT enqueue stage B; Claude adjudicates stage A first.",
    ],
    "hard_limits": [
        "No change to gate thresholds, verdict logic, the DL-089 sealed selection rule, opt_census.py semantics for DL089 programs, or any existing work_item row; append-only",
        "No EA source or binary change; the sweep is inputs-only on the existing QM5_41398 EX5 (sha pinned in the declaration)",
        "No manual terminal start; cells run only under the governed worker; never T_Live; RISK_FIXED=1000 / RISK_PERCENT=0 as in the baseline setfile",
        "Commit with explicit pathspecs, LF, co-author trailer; RESULT line in docs/ops/OPEN_ITEMS_STATUS.md with paths; every claim with a file path",
    ],
    "acceptance": [
        "declaration.json exists with plan commit hash + sha256 pins; window_sweep.py plan/enqueue/report work with --help",
        "420 stage-A OPT_CENSUS rows enqueued idempotently (second run = 0 new rows), payload accepted by the worker: at least one cell claimed and MEASURED with summary.json in the standard layout",
        "report produces the surface CSV on partial data with explicit not-yet-measured lists",
        "Touched worker/scheduler lines (if any) listed with rationale; no DL089 behaviour change (existing DL089 dry-run/plan output identical before/after, evidence attached)",
    ],
    "expected_artifact": "tools/strategy_farm/window_sweep.py + declaration.json + docs/ops/evidence/2026-09-XX_window_sweep_stageA_enqueue.md",
    "evidence": [PLAN, "tools/strategy_farm/opt_census.py", "tools/strategy_farm/opt_census_select.py", "tools/strategy_farm/dl089_scheduling.py", "D:/QM/reports/work_items/bc035c74-0000-5a7f-9c21-69a5e92b9529/QM5_41398/20260909_143930/summary.json (cell evidence example)"],
}

if __name__ == "__main__":
    for _ in range(6):
        r = subprocess.run(["python", "tools/strategy_farm/agent_router.py", "enqueue", "ops_issue", "--priority", "92",
                            "--assigned-agent", "codex", "--payload-json", json.dumps(T, ensure_ascii=False)],
                           capture_output=True, text=True, cwd=REPO)
        if r.returncode == 0:
            print("enqueue ok", json.loads(r.stdout)["task_id"])
            break
        print("retry", r.stderr.strip()[-200:])
        time.sleep(8)
