"""Enqueue the two Astra tickets for the OWNER implementation package v1.0 (2026-09-07 ~10:55Z):
A = Strategy Console v4 on the QM5_11421 FTMO demo canary, B = website design system on the local 8772 work copy.
Pattern: agent_router enqueue ops_issue + route-many (as for 4bdcbb91 / 203f9d3c).
"""
import json
import subprocess

REPO = "C:/QM/repo"
PKG = "docs/design/qm_implementation_package_v1.0"
COMMON = {
    "requested_by": "OWNER via claude-session-018mXkPPkaHQ2fPuduPCBcWc",
    "owner_instruction_utc": "2026-09-07T10:55:00Z",
    "owner_instruction": "Wir haben ueber das MQL5 EA Design und das Website Design nochmal drueber gearbeitet. Gib das alles an Astra zur Implementierung und Umsetzung (wieder am Test EA auf FTMO).",
    "model_tier": "astra",
    "codex_reasoning_effort": "xhigh",
    "package_root": PKG,
    "package_intake_commit": "9bd0bea521",
    "package_manifest": PKG + "/MANIFEST_SHA256.txt (27/27 verified at intake; docx/pdf parked under D:/QM/design/qm_implementation_package_v1.0/)",
}
A = dict(COMMON, **{
    "title": "Strategy Console v4 (Astra, OWNER implementation package 2026-09-07): port the QuantMechanica design system (design guideline v1.0, QMDesignTokens/QMDashboardModel/QMStrategyConsole contract, final mockup) into the V5 framework panel and ship it artifact-only on the QM5_11421 FTMO demo canary",
    "summary": "The OWNER and an external design session produced QuantMechanica_Implementation_Package_v1.0 (repo copy under " + PKG + "). It is the binding design baseline for the on-chart EA surface: a 'Strategy Console' with a fixed hierarchy (wordmark, STRATEGY CONSOLE, strategy title + timeframe, primary state card, two-column Filter Gate, Risk, state-adaptive LIVE, Today/Week strip, footer), FULL/COMPACT/MINIMAL modes, a token palette shared with the website (Carbon #171A21, Ink #0F172A, Quant Green #0A8A5B / Dark #087247, Slate #677185, Muted #8B95A7, Cloud #F5F7F9, Surface #FFFFFF, Border #DCE2E8 / Strong #C8D0DA, Signal Blue #3B6CF6, Positive #0B7A53, Negative #B8454D, Warning #996515, Candle Up #0E9F7A, Candle Down #F0545E, Range Border #6B8FD8, Range Fill #EDF3FF), Segoe UI typography, 4/8/12/16/24 px rhythm, 1 px separators, white chart, grid off, volumes off, Signal Blue current price. The package's mql5/ folder is a REFERENCE implementation from a foreign EA project (QuantRangePRO -> 'OHLC Daily Squeeze Reversal', IFilter/IStrategy architecture): do NOT install or compile it; port its contract (snapshot struct -> renderer, tokens header, modes, performance rules) into the V5 framework files that already carry Signature Panel v3 (framework/include/QM/QM_ChartPanel.mqh, QM_ChartScheme.mqh, QM_FrameworkSetChartUISuppressed in QM_Common). The package's pattern-filter cache correction and the foreign strategy files are out of scope.",
    "requirements": [
        "Read first: " + PKG + "/docs/QuantMechanica_Design_Guideline_MQL5_Web_v1.0.md (sections 1-16 and 24 are binding), " + PKG + "/reference/Strategy_Console_Final_Mockup.png, " + PKG + "/mql5/Include/QMDesignTokens.mqh, QMDashboardModel.mqh, QMStrategyConsole.mqh, QM_OHLCDailySqueezeReversal_Config.mqh (reference only), " + PKG + "/website/quantmechanica-design-tokens.json (cross-platform token source of truth), " + PKG + "/README_Integration.md, plus the V5 state of the art: docs/ops/evidence/2026-09-07_signature_panel_v3/README.md and docs/ops/evidence/2026-09-07_signature_panel_v2_spec/README.md.",
        "Architecture (guideline 15): Strategy/Filters/Risk -> structured snapshot struct (V5 name, e.g. QM_ConsoleSnapshot in a new framework/include/QM/QM_ConsoleModel.mqh) -> renderer (QM_ChartPanel.mqh becomes the Strategy Console renderer, or a new QM_StrategyConsole.mqh with QM_ChartPanel.mqh kept as a thin adapter). Tokens: new framework/include/QM/QM_DesignTokens.mqh mirroring quantmechanica-design-tokens.json value for value (document every deviation). The renderer never parses strategy decisions from strings, never calls filters or the governor for display, never changes trading logic (Visibility != Logic, guideline 8.5 / spec 9).",
        "Hierarchy (guideline 9) in FULL mode: 1 wordmark (Quant in Carbon, Mechanica in Quant Green), 2 STRATEGY CONSOLE, 3 strategy title + timeframe from the EA identity (for QM5_11421 use its registered strategy name and chart timeframe; never a hard-coded string), 4 primary state card (state word, reason line, next meaningful event, account mode DEMO/LIVE + symbol, as in the mockup), 5 two-column Filter Gate, 6 Risk, 7 LIVE only when an open position or actionable pending order exists (no fixed empty slots), 8 Today/Week strip, 9 '(c) QuantMechanica' + version. No license hash, no login number, no support text, no debug mode, no heartbeat block.",
        "Filter Gate (guideline 11, spec 2): ONLY gates that actually participate in this EA's trade admission in the V5 framework - derive them from QM_Common and the EA (news live filter with the native MT5 calendar, governor/kill switch when bound, Friday close, spread, session/time window, max positions, whatever is really enforced). Row grammar 'Label - concise reason   STATE' with states PASS/BLOCK/WARN/OFF/N-A/WAIT/ERROR/STALE (OFF is not PASS, N/A is not OFF). No decorative gates.",
        "Risk (guideline 12): Next trade (% and money), Open exposure to the actual SL via OrderCalcProfit (account currency, broker-contract aware), Stop basis. Show governor daily-loss / max-loss room ONLY when the FTMO governor is bound and actually enforcing for this magic; otherwise omit the line (no fake 3 % limit).",
        "PERFORMANCE: the guideline asks for one restrained Today/Week strip; the OWNER explicitly demanded on 2026-09-07 ~09:00 (Signature Panel v3, task 4bdcbb91) trades so far, P/L with this EA, win rate, profit factor, max drawdown and streaks. Resolution: FULL mode keeps the v3 PERFORMANCE table (cached deal-history scan, <= 1 scan per 30 s, never in OnTick) rendered in the package's grid grammar under the Today/Week strip; COMPACT shows only the Today/Week strip; MINIMAL shows brand + state + next event. Document this reconciliation in the evidence.",
        "Modes and inputs (spec 3): inputs InpUseVisualization, InpDashboardMode FULL/COMPACT/MINIMAL, InpVisualScale 80-150, InpShowActiveRange, InpShowStrategyLevels, InpShowTradeLevels, InpShowTradeMarkers (V5 input naming convention is allowed, semantics identical); a 'View' chart button cycles FULL -> COMPACT -> MINIMAL -> FULL (presentation only, OnChartEvent, never touches trading state). Historical setups off by default.",
        "Chart system (guideline 13, spec 4): QM_ChartScheme.mqh applies white background, grid off, volumes off, candle up #0E9F7A / down #F0545E, current price line #3B6CF6, and restores the previous scheme on deinit; strategy levels (entry/SL/TP) as direct labels only while exposure exists; no EMA/BB/session boxes/ICT markers unless the EA actually consumes them.",
        "Language and formats: product UI copy in English per guideline 4 (WAITING FOR SETUP, TRADE BLOCKED, 'Session - Trading open PASS' reason-first rule, no emoji, ASCII object text). Numbers stay in the OWNER-mandated de-DE formatter family from v3 (100.000,00 / 0,31 %) with an input to switch to en-US for a future MQL5 Market release; the formatter self-test stays in the compile probe.",
        "Safety contract (unchanged from v2/v3): timer-only refresh (OnTimer + OnTradeTransaction invalidation), tester-inert, full bypass under optimization, fail-inert (any renderer error may never abort OnInit or change an order - one Abnormal termination happened on the v1 canary), exactly ONE panel (QM_ChartUI suppressed before either renderer; object census in the evidence), deterministic object names, update-in-place instead of delete/recreate, one ChartRedraw per cycle.",
        "Canary delivery: artifact-only compile with the FTMO MetaEditor under D:/QM/ftmo/compile_probe_console_v4_<stamp>/ (pattern: D:/QM/ftmo/compile_probe_panel_v3_header_20260907_r3), install ONLY into the FTMO demo terminal data dir 81A933A9AFC5DE3C23B15CAB19C63850 (Experts/QM_FTMO + presets in MQL5/Presets), install receipt JSON with sha256 of the EX5 in both locations; framework/EAs/*.ex5 untouched (state it with sha256 before/after), no T_Live, no T1-T10, no AutoTrading. Provide the OWNER re-attach instruction as three lines.",
        "Evidence: docs/ops/evidence/2026-09-07_strategy_console_v4/README.md with: token mapping table (JSON token -> MQL constant -> value), full text mockups with realistic values for FULL, COMPACT and MINIMAL, the gate inventory with the code path proving each gate is real, the reconciliation notes (PERFORMANCE table, de-DE numbers, any deviation from the package), compile log, object census, install receipt, test list. Commit on an agents/codex-* branch with explicit pathspecs, LF line endings, co-author trailer; never stage framework/registry/dxz23_execution_contracts.json.",
        "Acceptance (CEO review): compile clean under the FTMO MetaEditor; single panel; hierarchy and palette match the package mockup; no fake gates or risk lines; performance table present in FULL; three modes render; formatter and snapshot self-tests pass; demo receipt sha256 matches; framework EX5 untouched; zero trading-logic diff (git diff of the EA's trading code paths shows only the visualization hooks).",
    ],
    "evidence": [PKG + "/docs/QuantMechanica_Design_Guideline_MQL5_Web_v1.0.md", PKG + "/reference/Strategy_Console_Final_Mockup.png", PKG + "/mql5/Include/QMStrategyConsole.mqh", PKG + "/mql5/Include/QMDashboardModel.mqh", PKG + "/mql5/Include/QMDesignTokens.mqh", PKG + "/website/quantmechanica-design-tokens.json", "framework/include/QM/QM_ChartPanel.mqh", "framework/include/QM/QM_ChartScheme.mqh", "docs/ops/evidence/2026-09-07_signature_panel_v3/README.md", "docs/ops/evidence/2026-09-07_signature_panel_v2_spec/README.md"],
    "required_capabilities": ["code", "ops", "research"],
})
B = dict(COMMON, **{
    "title": "Website design system v1.0 (Astra, OWNER implementation package 2026-09-07): apply quantmechanica-design-tokens.css / -components.css / -tokens.json and the web guideline (sections 17-21) to the local site work copy on http://127.0.0.1:8772/ - one brand with the Strategy Console; NO deploy",
    "summary": "The OWNER's implementation package (repo copy under " + PKG + "/website/) defines the website side of the QuantMechanica brand system: Inter typography, Quant Green #0A8A5B as brand accent / primary CTA, white Surface + Cloud #F5F7F9, hairline borders #DCE2E8, Signal Blue #3B6CF6 for information, 1240 px content width, 64 px restrained navigation, hero with eyebrow 'SYSTEMATIC - TESTED OPENLY', headline 'The Quantitative Edge.' (campaign line, not a product name), one proof paragraph, one primary green CTA, one secondary text link, evidence-led sections with real counts, chart grammar identical to MT5 (candle up #0E9F7A, down #F0545E, range #6B8FD8 / fill #EDF3FF), WCAG AA, status never colour-only, prefers-reduced-motion respected. The package states explicitly that the green editorial direction is the anchor and that no separate steel-blue 'software' brand may exist - this supersedes the v5 paper/ink/steel #2954d4 restyle of 2026-09-05 on the site. Apply it to the current local work copy C:/QM/deploy/qm-ops-refresh/tools/site-build/homepage-v4 (served on 8772) including the archive list and the 3.339 detail pages generated by build_archive_v31.py, the blog pages and all secondary pages in the shared shell.",
    "requirements": [
        "Read first: " + PKG + "/website/README_Web_Implementation.md, quantmechanica-design-tokens.css, quantmechanica-components.css, quantmechanica-design-tokens.json, and " + PKG + "/docs/QuantMechanica_Design_Guideline_MQL5_Web_v1.0.md sections 2-7 and 17-24; then the current site state (docs/ops/OPEN_ITEMS_STATUS.md Nachtraege 05.09. 16:48Z, 17:32Z, 18:56Z, 20:18Z) and the funnel data public-data/funnel-stats.json.",
        "Load order per README: tokens css first, components css second; refactor style.css so that every existing alias resolves to a package token (no second palette left behind; grep for #2954d4 and the old font stack must return 0 hits in the shipped CSS). Fonts: Inter from fonts.googleapis.com with the Segoe UI / Helvetica Neue / Arial fallback; Fraunces / IBM Plex are retired (the OWNER package does not allow them).",
        "Keep what the OWNER approved on 2026-09-05 and restyle it in the new grammar: headline 'The Quantitative Edge.', records block with real numbers from funnel-stats.json, the animated left-to-right evidence funnel with phases, gates and strategies as balls, the vertical mechanics list, the candle background animation in the header (now in the package candle colours). Reconciliation for motion: the guideline requires prefers-reduced-motion to be respected; the VPS Chrome reports reduced motion falsely, so keep the visible Play/Pause control and default to a static frame under reduced motion, with a one-click play. Document it.",
        "Hero and navigation per guideline 17: 4-6 nav items, no CTA stack; eyebrow 'SYSTEMATIC - TESTED OPENLY'; one green primary CTA (pill radius allowed), one secondary text link. Cards 16 px radius, controls 8 px, rhythm 4/8/12/16/24/32/48/64/96/128 px.",
        "Evidence sections per guideline 18-19: real counts and gate outcomes only; illustrative charts labelled 'illustrative'; real evidence visually distinguishable; Strategy Console screenshots may be placeholders labelled as such until the v4 canary screenshot exists (no fake dashboards, no glowing terminals, no 'AI-powered' / 'smart money' / 'institutional grade' wording).",
        "Responsive and accessibility per guideline 20-21: 1240 px max, stacked mobile, 44 px targets, WCAG AA contrast for body text (measure and list the ratios), visible focus, no essential copy inside images, captions for screenshots.",
        "Archive list and detail pages: regenerate through build_archive_v31.py with the new shell; the exposure denylist (internal pseudo-symbols QM5_*/FX8/SLOT*) stays; exposure grep must be 0 over all pages.",
        "Verification: rebuild the local site, serve on 8772, probe with a CDP screenshot set (home desktop 1440, home mobile 390, archive list, one detail page, one blog page) before and after, contrast table, offline Lighthouse-style checks if available, grep results. Evidence README under docs/ops/evidence/2026-09-07_website_design_system_v1/README.md with the token mapping (old alias -> new token), the screenshot list and the reconciliation notes. Commit the site sources on an agents/codex-* branch with explicit pathspecs and LF endings; NO deploy - Mission-Control card OWNER-DEC-WEBSITE-DEPLOY-20260905 is still open.",
        "Acceptance (CEO review): one palette (package tokens) across all page types; Inter loaded; hero structure per guideline; funnel + mechanics + candle header preserved and restyled; contrast AA documented; exposure grep 0; archive regenerated; 8772 serves the new build; no deploy.",
    ],
    "evidence": [PKG + "/website/README_Web_Implementation.md", PKG + "/website/quantmechanica-design-tokens.css", PKG + "/website/quantmechanica-components.css", PKG + "/website/quantmechanica-design-tokens.json", PKG + "/docs/QuantMechanica_Design_Guideline_MQL5_Web_v1.0.md", "public-data/funnel-stats.json", "docs/ops/OPEN_ITEMS_STATUS.md"],
    "required_capabilities": ["code", "ops"],
})

if __name__ == "__main__":
    for prio, payload in ((90, A), (86, B)):
        r = subprocess.run(["python", "tools/strategy_farm/agent_router.py", "enqueue", "ops_issue", "--priority", str(prio),
                            "--payload-json", json.dumps(payload, ensure_ascii=False)], capture_output=True, text=True, cwd=REPO)
        print("enqueue rc", r.returncode, (r.stdout + r.stderr).strip()[-400:])
    r = subprocess.run(["python", "tools/strategy_farm/agent_router.py", "route-many", "--max-routes", "3"], capture_output=True, text=True, cwd=REPO)
    print("route rc", r.returncode, (r.stdout + r.stderr).strip()[-1500:])
