import os

wiki_base = "G:/My Drive/QuantMechanica - Company Reference/09 Strategy Wiki"
strat_dir = os.path.join(wiki_base, "strategies")

STRATEGIES = [
    # slug, filename, ea_id, src_id, status, g0_status, pipeline_phase,
    # primary_concept, secondary_concept, source_node, summary, timeframe, markets, mechanisms
    {
        "filename": "chan-at-bb-pair.md",
        "ea_id": "TBD",
        "slug": "chan-at-bb-pair",
        "src_id": "SRC05_S01",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "mean-reversion",
        "secondary_concept": "pair-trade",
        "timeframe": "D1",
        "markets": "ETF/commodity pair (GLD-USO proxy)",
        "source_ref": "Chan AT (2013), Ch 3 Ex 3.2 -- Bollinger Band pair-spread MR, p. 70-72",
        "entry": "Z-score of OLS-hedged spread crosses +-1-sigma; exit at 0-sigma (mean)",
        "stop": "None (no native stop; QM_KillSwitch + account MAX_DD are backstop)",
        "sizing": "1 unit spread; V5 risk framework at sizing-time",
        "summary": "Bollinger-band mean-reversion on a daily rolling-OLS-hedged pair spread. Chan reports APR 17.8% / Sharpe 0.96 on GLD-USO. V5 candidate pairs: GOLD.DWX/OIL.DWX.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-buy-on-gap.md",
        "ea_id": "TBD",
        "slug": "chan-at-buy-on-gap",
        "src_id": "SRC05_S03",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "mean-reversion",
        "secondary_concept": "trend-following",
        "timeframe": "D1 (open-to-close intraday)",
        "markets": "SPX stocks cross-sectional (V5: V5-architecture-CHALLENGED)",
        "source_ref": "Chan AT (2013), Ch 4 Ex 4.1 -- Buy-on-Gap SPX, p. 93-96",
        "entry": "Top-10 stocks with largest gap-DOWN below prior low by 1-sigma AND above 20-day MA; BUY at open",
        "stop": "None from source; time-stop at session close",
        "sizing": "Equal capital / topN=10; V5 framework",
        "summary": "Cross-sectional intraday gap-fade: buy top-10 most-gapped-down SPX stocks at open, exit at close. Chan reports APR 8.7% / Sharpe 1.5. V5-architecture-CHALLENGED (cross-sectional universe).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-cal-spread.md",
        "ea_id": "TBD",
        "slug": "chan-at-cal-spread",
        "src_id": "SRC05_S06",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "mean-reversion",
        "secondary_concept": "range-trade",
        "timeframe": "D1",
        "markets": "CL futures calendar spread (Variant A); VX back/front ratio (Variant B)",
        "source_ref": "Chan AT (2013), Ch 5 Ex 5.4 -- Calendar Spread MR, p. 115-127",
        "entry": "Z-score of roll-return gamma; long far/short near when z<0, flip when z>0",
        "stop": "Roll-forward 10 days before near-contract expiry; hold ~63 trading days",
        "sizing": "1 unit; V5 framework",
        "summary": "Mean-reversion of futures calendar spread via roll-return Z-score signal. CL: APR 8.3% / Sharpe 1.3. VX variant: APR 17.7% / Sharpe 1.5. V5-architecture-CHALLENGED (futures calendar structure).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-fstx-gap-mom.md",
        "ea_id": "TBD",
        "slug": "chan-at-fstx-gap-mom",
        "src_id": "SRC05_S12",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "trend-following",
        "secondary_concept": "",
        "timeframe": "D1 (open-to-close intraday)",
        "markets": "Futures (single-symbol, session-open gap)",
        "source_ref": "Chan AT (2013) -- Futures opening-gap momentum",
        "entry": "Gap UP above prior bar: go LONG at open; gap DOWN below prior bar: go SHORT; exit at close",
        "stop": "None from source; time-stop at session close",
        "sizing": "V5 framework",
        "summary": "Futures opening-gap momentum: go WITH the gap direction at open, exit close. Opposite of gap-fade (chan-at-buy-on-gap). Single-symbol futures.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "chan-at-fx-coint-pair.md",
        "ea_id": "TBD",
        "slug": "chan-at-fx-coint-pair",
        "src_id": "SRC05_S05",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "pair-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "D1",
        "markets": "FX pairs (cointegrating; AUD/CAD or similar)",
        "source_ref": "Chan AT (2013), Ch 5 -- FX cointegration pair MR",
        "entry": "Z-score of cointegrated FX pair spread crosses entry threshold; exit at 0 (mean)",
        "stop": "Half-life time-stop (Chan convention)",
        "sizing": "V5 framework",
        "summary": "Cointegration pair trade on FX. Uses Johansen or cadf test for pair selection. V5 Darwinex-native candidate pairs available.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-kf-pair.md",
        "ea_id": "TBD",
        "slug": "chan-at-kf-pair",
        "src_id": "SRC05_S02",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "pair-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "D1",
        "markets": "Any cointegrating pair (equities, ETFs, FX)",
        "source_ref": "Chan AT (2013), Ch 3 -- Kalman Filter dynamic hedge pair MR",
        "entry": "Kalman-filter posterior hedge ratio + spread Z-score; entry at +-1-sigma, exit at 0",
        "stop": "No native stop; Kalman tracking bounds the hedge ratio drift",
        "sizing": "Kalman observation noise variance as position-sizing input; V5 framework",
        "summary": "Dynamically-hedged pair using Kalman filter. Hedge ratio updated every bar. Distinguished from chan-at-bb-pair (static OLS hedge) by continuous hedge-ratio adaptation.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-roll-arb-etf.md",
        "ea_id": "TBD",
        "slug": "chan-at-roll-arb-etf",
        "src_id": "SRC05_S08",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "pair-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "D1",
        "markets": "Leveraged ETF pairs (e.g., SSO/SDS, or ETF vs underlying)",
        "source_ref": "Chan AT (2013), Ch 5 -- ETF roll-return arbitrage",
        "entry": "Signal-reversal when roll-return Z-score crosses threshold",
        "stop": "No native stop from source",
        "sizing": "V5 framework",
        "summary": "ETF roll-return arbitrage exploiting leveraged-ETF decay and the roll-return differential between ETF and its underlying futures.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-spy-arb.md",
        "ea_id": "TBD",
        "slug": "chan-at-spy-arb",
        "src_id": "SRC05_S04",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "pair-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "D1",
        "markets": "SPY ETF vs S&P 500 futures (or equivalent)",
        "source_ref": "Chan AT (2013) -- SPY/futures cointegration arb",
        "entry": "Z-score of SPY-futures cointegrated spread; entry at +-1-sigma",
        "stop": "No native stop",
        "sizing": "V5 framework",
        "summary": "SPY/futures stat-arb on the tracking error between SPY and S&P futures contract. V5-architecture note: requires DWX index vs futures equivalent.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "chan-at-ts-mom-fut.md",
        "ea_id": "TBD",
        "slug": "chan-at-ts-mom-fut",
        "src_id": "SRC05_S07",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "trend-following",
        "secondary_concept": "",
        "timeframe": "D1 / monthly",
        "markets": "Futures universe (commodities, financials, FX futures)",
        "source_ref": "Chan AT (2013), Ch 5 -- Time-series momentum on futures",
        "entry": "12-month return positive: LONG; negative: SHORT. Rebalance monthly.",
        "stop": "Signal reversal (position flips monthly with signal)",
        "sizing": "Equal risk / vol-scaled; V5 framework",
        "summary": "Time-series momentum: long futures with positive 12-month return, short with negative. Classic trend-following. V5-architecture-CHALLENGED (cross-asset futures universe).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-vx-es-roll-mom.md",
        "ea_id": "TBD",
        "slug": "chan-at-vx-es-roll-mom",
        "src_id": "SRC05_S09",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "trend-following",
        "secondary_concept": "pair-trade",
        "timeframe": "D1",
        "markets": "VX futures (CBOE VIX futures) vs ES (S&P futures)",
        "source_ref": "Chan AT (2013), Ch 5 -- VX/ES roll momentum",
        "entry": "Roll-return momentum signal: long VX / short ES when VX roll return positive",
        "stop": "Signal reversal",
        "sizing": "V5 framework",
        "summary": "VX/ES roll-return momentum: exploit the roll differential between volatility futures and equity index futures. V5-architecture-CHALLENGED (requires VX futures).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT -- awaiting CEO + QB review",
    },
    {
        "filename": "chan-at-xs-mom-fut.md",
        "ea_id": "TBD",
        "slug": "chan-at-xs-mom-fut",
        "src_id": "SRC05_S10",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "trend-following",
        "secondary_concept": "",
        "timeframe": "D1 / monthly",
        "markets": "Futures universe (cross-sectional)",
        "source_ref": "Chan AT (2013), Ch 5 -- Cross-sectional momentum on futures",
        "entry": "Long top-quintile futures by 12-month return, short bottom-quintile; rebalance monthly",
        "stop": "Signal reversal",
        "sizing": "Equal risk / vol-scaled; V5 framework",
        "summary": "Cross-sectional momentum on futures: long relative winners, short relative losers. V5-architecture-CHALLENGED (cross-asset futures universe).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "chan-at-xs-mom-stock.md",
        "ea_id": "TBD",
        "slug": "chan-at-xs-mom-stock",
        "src_id": "SRC05_S11",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "chan-algorithmic-trading-2013",
        "primary_concept": "trend-following",
        "secondary_concept": "",
        "timeframe": "D1 / monthly",
        "markets": "Stock universe (SPX or similar; cross-sectional)",
        "source_ref": "Chan AT (2013), Ch 4 -- Cross-sectional stock momentum",
        "entry": "Long top-quintile stocks by 12-month return (skip last month), short bottom-quintile; rebalance monthly",
        "stop": "Signal reversal",
        "sizing": "Equal risk / vol-scaled; V5 framework",
        "summary": "Cross-sectional stock momentum (Jegadeesh-Titman style). Long relative winners, short relative losers. V5-architecture-CHALLENGED (cross-sectional stock universe).",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "QM5_1017_chan-pairs-stat-arb.md",
        "ea_id": "1017",
        "slug": "chan-pairs-stat-arb",
        "src_id": "SRC02_S01",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "chan-quantitative-trading-2009",
        "primary_concept": "pair-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "D1",
        "markets": "GLD/GDX cointegrating pair (gold ETF / gold miners ETF)",
        "source_ref": "Chan QT (2009), Ch 3 -- GLD/GDX stat-arb, cadf cointegration",
        "entry": "cadf cointegration test on rolling window; enter on Z-score +-2 sigma, exit at 0 or half-life time-stop",
        "stop": "Half-life time-stop; QM_KillSwitch as catastrophic backstop",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "GLD/GDX cointegration stat-arb. cadf test gates entries. CEO-APPROVED (friday_close waiver granted). ea_id=QM5_1017. In P2 pipeline.",
        "r1": "UNKNOWN",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "PASS (CEO ACCEPT; friday_close waiver granted)",
    },
    {
        "filename": "davey-baseline-3bar.md",
        "ea_id": "TBD",
        "slug": "davey-baseline-3bar",
        "src_id": "SRC01_S03",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "G0",
        "source_node": "davey-building-algo-trading-systems",
        "primary_concept": "mean-reversion",
        "secondary_concept": "breakout",
        "timeframe": "H1",
        "markets": "EURUSD.DWX (Davey: any liquid futures)",
        "source_ref": "Davey (2014), Appendix A Strategy 1 -- Baseline 3-bar MR",
        "entry": "3-bar pattern trigger (Davey baseline); mean-reversion bias",
        "stop": "ATR-based hard stop (V5 default)",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Davey 3-bar baseline strategy. CEO-APPROVED (QUA-276, 2026-04-27). ea_id TBD pending P1 build. Deployed on EURUSD H1 in P2 testing.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-27",
        "g0_verdict": "APPROVED (CEO interim, QUA-276)",
    },
    {
        "filename": "QM5_1004_davey-es-breakout.md",
        "ea_id": "1004",
        "slug": "davey-es-breakout",
        "src_id": "SRC01_S04",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "davey-building-algo-trading-systems",
        "primary_concept": "breakout",
        "secondary_concept": "trend-following",
        "timeframe": "D1 / H4",
        "markets": "ES (S&P 500 futures); V5: US500.DWX or equivalent",
        "source_ref": "Davey (2014), Appendix A Strategy 4 -- ES Channel Breakout",
        "entry": "Price breaks above/below N-bar high/low channel; enter with the breakout",
        "stop": "ATR trailing stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Davey ES channel breakout. ea_id=QM5_1004. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-27",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1013_lien-20day-breakout.md",
        "ea_id": "1013",
        "slug": "lien-20day-breakout",
        "src_id": "SRC04_S07",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "breakout",
        "secondary_concept": "trend-following",
        "timeframe": "D1",
        "markets": "Major FX pairs (EURUSD, GBPUSD, etc.); Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 9 -- 20-day Donchian breakout",
        "entry": "Close above 20-day high (long) / below 20-day low (short)",
        "stop": "ATR hard stop + ATR trailing stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "20-day Donchian channel breakout on FX. ea_id=QM5_1013. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1016_lien-carry-trade.md",
        "ea_id": "1016",
        "slug": "lien-carry-trade",
        "src_id": "SRC04_S11",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "trend-following",
        "secondary_concept": "",
        "timeframe": "D1 / W1",
        "markets": "High-yielding FX pairs (AUD/JPY, NZD/JPY, etc.); Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 13 -- FX Carry Trade",
        "entry": "Long high-yield / short low-yield currency when carry signal is positive",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "FX carry trade: long high-interest-rate currency, short low-interest-rate currency. ea_id=QM5_1016. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1014_lien-channels.md",
        "ea_id": "1014",
        "slug": "lien-channels",
        "src_id": "SRC04_S08",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "breakout",
        "secondary_concept": "range-trade",
        "timeframe": "H1 / H4",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 10 -- Narrow channel breakout",
        "entry": "Narrow range consolidation forms (N bars within ATR threshold); enter on breakout above/below range",
        "stop": "ATR hard stop opposite side of range; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Lien narrow-channel breakout: narrow range consolidation then directional breakout. ea_id=QM5_1014. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "lien-dbb-pick-tops.md",
        "ea_id": "TBD",
        "slug": "lien-dbb-pick-tops",
        "src_id": "SRC04_S02a",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "volatility-filter",
        "secondary_concept": "mean-reversion",
        "timeframe": "H1 / H4",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015) -- Double Bollinger Band: pick-tops variant",
        "entry": "Price enters outer Bollinger Band zone (>+2SD or <-2SD) -- fade / pick top or bottom",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline; V5 framework",
        "summary": "Double Bollinger Band: fade outer band (>2SD) to pick tops/bottoms. DRAFT pending G0 CEO review.",
        "r1": "UNKNOWN",
        "r2": "UNKNOWN",
        "r3": "UNKNOWN",
        "r4": "UNKNOWN",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "lien-dbb-trend-join.md",
        "ea_id": "TBD",
        "slug": "lien-dbb-trend-join",
        "src_id": "SRC04_S02b",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "volatility-filter",
        "secondary_concept": "trend-following",
        "timeframe": "H1 / H4",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015) -- Double Bollinger Band: trend-join variant",
        "entry": "Price reclaims middle band zone (between +1SD and +2SD) from above -- trend continuation buy",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline; V5 framework",
        "summary": "Double Bollinger Band trend-join: enter when price reclaims middle-to-outer band zone as trend continuation. DRAFT pending G0 CEO review.",
        "r1": "UNKNOWN",
        "r2": "UNKNOWN",
        "r3": "UNKNOWN",
        "r4": "UNKNOWN",
        "g0_date": "2026-04-28",
        "g0_verdict": "DRAFT",
    },
    {
        "filename": "QM5_1009_lien-fade-double-zeros.md",
        "ea_id": "1009",
        "slug": "lien-fade-double-zeros",
        "src_id": "SRC04_S03",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "mean-reversion",
        "secondary_concept": "",
        "timeframe": "M15 / H1",
        "markets": "Major FX pairs with double-zero levels (x.x000); EURUSD.DWX, GBPUSD.DWX, etc.",
        "source_ref": "Lien (2015), Ch 10 -- Fading the Double Zeros",
        "entry": "Price approaches double-zero level (x.x000): fade the level; stop beyond level",
        "stop": "ATR hard stop beyond double-zero level; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Fade round-number double-zero levels on FX. ea_id=QM5_1009. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1012_lien-fader.md",
        "ea_id": "1012",
        "slug": "lien-fader",
        "src_id": "SRC04_S06",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "mean-reversion",
        "secondary_concept": "breakout",
        "timeframe": "H1 / H4",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 11 -- Failed-breakout Fader",
        "entry": "Breakout above resistance or below support that then fails to hold; fade the failed breakout",
        "stop": "ATR hard stop; ATR trailing stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Failed-breakout fade: enter against a breakout that reverses back inside the range. ea_id=QM5_1012. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1011_lien-inside-day-breakout.md",
        "ea_id": "1011",
        "slug": "lien-inside-day-breakout",
        "src_id": "SRC04_S05",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "breakout",
        "secondary_concept": "",
        "timeframe": "D1",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 11 -- Inside Day narrow-range breakout",
        "entry": "Today's range is contained within yesterday's range (inside day); enter on breakout above/below today's high/low",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Inside-day breakout on FX: compressed range then directional break. ea_id=QM5_1011. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1015_lien-perfect-order.md",
        "ea_id": "1015",
        "slug": "lien-perfect-order",
        "src_id": "SRC04_S09",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "trend-following",
        "secondary_concept": "breakout",
        "timeframe": "H1 / H4",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 13 -- Perfect Order MA alignment",
        "entry": "All three moving averages (8/21/55 EMA) aligned in trend direction -- enter on pullback",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Moving average perfect-order trend: all MAs aligned (8 > 21 > 55 for uptrend). ea_id=QM5_1015. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "QM5_1010_lien-waiting-deal.md",
        "ea_id": "1010",
        "slug": "lien-waiting-deal",
        "src_id": "SRC04_S04",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "P2",
        "source_node": "lien-day-trading-forex-market",
        "primary_concept": "range-trade",
        "secondary_concept": "mean-reversion",
        "timeframe": "H1",
        "markets": "Major FX pairs; Darwinex .DWX",
        "source_ref": "Lien (2015), Ch 12 -- Waiting for the Deal (intraday session pattern)",
        "entry": "Wait for the Asia session range to establish; enter at the extremes of that range during London open",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); RISK_FIXED $1000 baseline (P2); V5 framework",
        "summary": "Intraday session pattern: wait for Asia range then fade/trade London open extremes. ea_id=QM5_1010. CEO-APPROVED. In P2 pipeline.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "PASS",
        "r4": "PASS",
        "g0_date": "2026-04-28",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "williams-pinch-paunch.md",
        "ea_id": "TBD",
        "slug": "williams-pinch-paunch",
        "src_id": "SRC03_S17",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "G0",
        "source_node": "williams-long-term-secrets",
        "primary_concept": "volatility-filter",
        "secondary_concept": "breakout",
        "timeframe": "D1",
        "markets": "Futures / FX (Williams: any liquid market)",
        "source_ref": "Williams (1999), Inner Circle Workshop -- Pinch and Paunch top/bottom pattern",
        "entry": "Volatility squeeze (pinch) followed by expansion (paunch); enter on direction of expansion",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); V5 framework",
        "summary": "Larry Williams Pinch-and-Paunch: volatility compression then expansion entry. CEO-APPROVED. ea_id TBD pending P1 build.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-05-01",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "williams-pro-go.md",
        "ea_id": "TBD",
        "slug": "williams-pro-go",
        "src_id": "SRC03_S16",
        "card_status": "APPROVED",
        "g0_status": "APPROVED",
        "pipeline_phase": "G0",
        "source_node": "williams-long-term-secrets",
        "primary_concept": "trend-following",
        "secondary_concept": "breakout",
        "timeframe": "D1",
        "markets": "Futures / FX (Williams: any liquid market)",
        "source_ref": "Williams (1999), Inner Circle Workshop p. 18 -- Pro-Go indicator entry",
        "entry": "Pro-Go indicator triggers directional entry (momentum-based new-high/new-low pattern)",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); V5 framework",
        "summary": "Larry Williams Pro-Go: momentum entry on new-high/new-low pattern with Pro-Go indicator. CEO-APPROVED. ea_id TBD pending P1 build.",
        "r1": "PASS",
        "r2": "PASS",
        "r3": "UNKNOWN",
        "r4": "PASS",
        "g0_date": "2026-05-01",
        "g0_verdict": "APPROVED",
    },
    {
        "filename": "williams-vol-bo.md",
        "ea_id": "TBD",
        "slug": "williams-vol-bo",
        "src_id": "SRC03_S01",
        "card_status": "DRAFT",
        "g0_status": "PENDING",
        "pipeline_phase": "G0",
        "source_node": "williams-long-term-secrets",
        "primary_concept": "volatility-filter",
        "secondary_concept": "breakout",
        "timeframe": "D1",
        "markets": "Futures / FX (Williams: any liquid market)",
        "source_ref": "Williams (1999) -- Volatility Breakout strategy",
        "entry": "Today's range expands beyond N% of recent average range; enter in direction of the expansion",
        "stop": "ATR hard stop; V5 framework",
        "sizing": "RISK_PERCENT (live); V5 framework",
        "summary": "Larry Williams volatility expansion breakout: enter when daily range expands significantly beyond recent average. DRAFT pending G0 CEO review.",
        "r1": "UNKNOWN",
        "r2": "UNKNOWN",
        "r3": "UNKNOWN",
        "r4": "UNKNOWN",
        "g0_date": "?",
        "g0_verdict": "DRAFT",
    },
]

def make_secondary_refs(s):
    refs = ['[[sources/%s]]' % s["source_node"]]
    concepts_refs = ['[[concepts/%s]]' % s["primary_concept"]]
    if s["secondary_concept"]:
        concepts_refs.append('[[concepts/%s]]' % s["secondary_concept"])
    return refs, concepts_refs

for s in STRATEGIES:
    source_refs, concept_refs = make_secondary_refs(s)
    src_yaml = "\n".join('  - "%s"' % r for r in source_refs)
    concept_yaml = "\n".join('  - "%s"' % c for c in concept_refs)
    concept_body = "\n".join(
        "- %s -- %s" % (c, "primary" if i == 0 else "secondary")
        for i, c in enumerate(concept_refs)
    )
    secondary_line = ""
    if s["secondary_concept"]:
        secondary_line = "- [[concepts/%s]] -- secondary" % s["secondary_concept"]

    related_strats = "- *TBD*"

    content = """---
ea_id: {ea_id}
slug: {slug}
type: strategy
sources:
{src_yaml}
concepts:
{concept_yaml}
indicators: []
g0_status: {g0_status}
r1_track_record: {r1}
r2_mechanical: {r2}
r3_data_available: {r3}
r4_ml_forbidden: {r4}
pipeline_phase: {pipeline_phase}
last_updated: 2026-05-08
---

# {slug}

## Quelle
- Source: [[sources/{source_node}]]
- Page / Timestamp: {source_ref}

## Mechanik

### Entry
{entry}

### Exit
Signal reversal or mean-reversion target (see card for detail)

### Stop Loss
{stop}

### Position Sizing
{sizing}

### Zusaetzliche Filter
Standard V5 framework: QM_KillSwitch, news filter, MAX_DD trip, Friday-close flatten.

## Concepts (was ist das fuer eine Strategie)
- [[concepts/{primary_concept}]] -- primary
{secondary_line}

## R1-R4 Bewertung
| Kriterium | Status | Begruendung |
|-----------|--------|------------|
| R1 Track Record | {r1} | {author} verifiable track record; see source node |
| R2 Mechanical | {r2} | Mechanical rule derived from source verbatim |
| R3 Data Available | {r3} | See markets note; Darwinex .DWX coverage TBD for some |
| R4 ML Forbidden | {r4} | No ML element; classical statistics / price-action rules |

## Pipeline-Verlauf
- G0: {g0_date}, {g0_verdict}

## Verwandte Strategien
{related_strats}

## Lessons Learned (waehrend Pipeline-Lauf)
- *See canonical source: C:/QM/repo/strategy-seeds/cards/{slug}_card.md*

---

*Knoten-Pflege: bei jeder Pipeline-Phase-Aenderung pipeline_phase aktualisieren + last_updated. Bei FAIL: pipeline_phase: DEAD + Lessons-Learned-Eintrag.*
""".format(
        ea_id=s["ea_id"],
        slug=s["slug"],
        src_yaml=src_yaml,
        concept_yaml=concept_yaml,
        g0_status=s["g0_status"],
        r1=s["r1"], r2=s["r2"], r3=s["r3"], r4=s["r4"],
        pipeline_phase=s["pipeline_phase"],
        source_node=s["source_node"],
        source_ref=s["source_ref"],
        entry=s["entry"],
        stop=s["stop"],
        sizing=s["sizing"],
        primary_concept=s["primary_concept"],
        secondary_line=secondary_line,
        author=s["source_node"].split("-")[0].capitalize(),
        g0_date=s["g0_date"],
        g0_verdict=s["g0_verdict"],
        related_strats=related_strats,
    )
    path = os.path.join(strat_dir, s["filename"])
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("STRATEGY:", s["filename"])

print("\nDone. Total:", len(STRATEGIES))
